"""Scaffold a new skill directory."""

from __future__ import annotations

import re
from pathlib import Path

NAME_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")
SKILL_CORE = Path(__file__).resolve().parent.parent
TEMPLATE = SKILL_CORE / "references" / "template.skill.md"


def scaffold(name: str, root: Path) -> Path:
    if not NAME_RE.match(name):
        raise ValueError(f"Invalid skill name '{name}'. Use lowercase, hyphens, digits.")

    dest = root / name
    if dest.exists():
        raise FileExistsError(f"Already exists: {dest}")

    dest.mkdir(parents=True)
    (dest / "references").mkdir()
    (dest / "scripts").mkdir()
    (dest / "assets").mkdir()

    ir_content = TEMPLATE.read_text(encoding="utf-8").replace("<skill-name>", name)
    (dest / "references" / "ir.md").write_text(ir_content, encoding="utf-8")

    eval_yaml = """tests:
  - id: T1
    description: compiled skill has core sections
    assert:
      sections: ["Quick Start", "Failure Modes"]
      not_contains: ["PLACEHOLDER"]
"""
    (dest / "references" / "eval.yaml").write_text(eval_yaml, encoding="utf-8")

    placeholder = f"""---
name: {name}
description: >-
  PLACEHOLDER — run `skill compile {name}` after editing references/ir.md
metadata:
  version: "0.1.0"
  status: experimental
  protocol: skill-protocol-v2
---

# {name.replace("-", " ").title()}

> Generated by `skill init`. Edit `references/ir.md`, then run `skill compile`.
"""
    (dest / "SKILL.md").write_text(placeholder, encoding="utf-8")
    return dest
